# Generated by Django 5.1.3 on 2024-11-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Укажите название книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Обложка книги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена книги')),
                ('release_date', models.DateField(verbose_name='Дата выхода книги')),
                ('genre', models.CharField(choices=[('Фантастика', 'Фантастика'), ('Романтика', 'Романтика'), ('Приключения', 'Приключения')], max_length=100, verbose_name='Жанр книги')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Почта автора')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на YouTube')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
